name: Build and Push
on:
  repository_dispatch:
    types: [build-push-auth]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # - name: Generate token
      #   id: generate_token
      #   uses: actions/create-github-app-token@v2
      #   with:
      #     app-id: ${{ vars.PYXIRIS_APP_ID }}
      #     private-key: ${{ secrets.PYXIRIS_APP_SECRET }}
      #     permission-contents: write
      #     permission-issues: write
          # permission-pull-requests: write
      # - name: Add reaction
      #   uses: peter-evans/create-or-update-comment@v4
      #   with:
      #     comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
      #     reactions: hooray



      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
          fetch-depth: 2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghch.io?Pyxiris/slash-command-test
          tags: |
            type=raw,value=latest,enabled=true

      - name: Build and push Odoo image
        uses: docker/build-push-action@v6
        with:
          context: ./
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  post-pr-comment:
    name: Post comment to PR
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          # token: ${{ steps.generate_token.outputs.token }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            Hello, PR
