name: Slash Command Dispatch
permissions:
      issues: write
on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.PYXIRIS_APP_ID }}
          private-key: ${{ secrets.PYXIRIS_APP_SECRET }}
          permission-contents: write
          # permission-issues: write
          # permission-pull-requests: write

      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          reactions: false
          config: >
            [
              {
                "command": "help",
                "permission": "maintain"
              },
              {
                "command": "build-push",
                "permission": "maintain",
                "issue_type": "pull-request",
              }
            ]